version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run: npm install
          name: Greeting
          command: echo Hello, world.
      - run: npm test
          name: Print the Current Time
          command: date
